### ISSUE TITLE
Fixing the signature check for installation sources

### ISSUE THREAD

**Issue by elfring** [openSUSE/libzypp#110]
[The tool “zypper 1.14.5”](https://github.com/openSUSE/zypper/commit/2eebf0c53110604f2ce7f07e8ddc033d292b88ad "Management for software packages") displays the message “Warning: File 'repomd.xml' from repository '…' is signed with an unknown key ''.” on my system.
I tried to clarify this questionable software situation already in [a forum](https://forums.opensuse.org/showthread.php/530920-Checking-signatures-for-installation-sources "Checking signatures for installation sources") (without a final solution so far).

I have taken another look at involved source files in the hope to get an explanation for a misssing information.
* [The function call “context.repoInfo().asUserString()”](https://github.com/openSUSE/zypper/blob/60e47cfbc5b68e6e69afe9b7df5c6621a9e0a795/src/callbacks/keyring.h#L188 "Checking askUserToAcceptUnknownKey()") provides an empty string.
* The item “repoInfo” is received by [the variable “info” of the constructor for the class “Downloader”](https://github.com/openSUSE/libzypp/blob/806402c2c8691d608a3e6397025c61249dd6350d/zypp/repo/Downloader.h#L39 "Constructor for the class “Downloader”"). Where is this object created?

**Comment by bzeller** [comment]
Could you provide your /var/log/zypper.log ? Could help us to pinpoint the problem

**Comment by bzeller** [comment]
Well of course you can use the gpg tool on the commandline to do the same check zypper executes.

```
mkdir -p /tmp/test
wget http://repourl/repodata/repomd.xml
wget http://repourl/repodata/repomd.xml.asc
wget http://repourl/repodata/repomd.xml.key
gpg --homedir /tmp/test --import repomd.xml.key 
gpg --homedir /tmp/test --verify repomd.xml.asc repomd.xml 
```

**Comment by elfring** [comment]
I have tried the following command variant out.

```
elfring@Sonne:/tmp> LANG=C && mkdir test-110 && cd test-110 && P=https://download.opensuse.org/tumbleweed/repo/oss/repodata/ && M=repomd.xml && wget $P$M $P$M.asc $P$M.key && gpg --homedir . --import $M.key && echo === && gpg --homedir . --verify $M.asc $M
```
…
```
gpg: Signature made Tue May 22 13:33:15 2018 CEST
gpg:                using RSA key B88B2FD43DBDC284
gpg: Good signature from "openSUSE Project Signing Key <opensuse@opensuse.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 22C0 7BA5 3417 8CD0 2EFE  22AA B88B 2FD4 3DBD C284
```


How should this software situation be clarified further?

**Comment by bzeller** [comment]
Well it was expected that the verification will work, since it works for most people just perfectly fine. 
Does that mean zypper can not verify the repomd.xml in https://download.opensuse.org/tumbleweed/repo/oss/ on your machine?

If that is still reproduceable for you then try to do a refresh and we can have a look at your zypper log file. It might show what key zypper tries to use to verify the repomd.xml in your case.

**Comment by elfring** [comment]
It seems that I can not use any of the published Tumbleweed repositories on my system at the moment because of the signature check failure.

* For which error message (or key information) would you be looking for in a “refreshed” log file?
* Should I try to add any debug output in the affected C++ source files?

**Comment by bzeller** [comment]
- I would start to look for strings the verifyFileSignatureWorkflow would print and then work my way through the messages to figure out the program flow
- Just the plain file without additional debug output would be a good start.

However I can not really help you without looking at the logfile myself, otherwise its just guesswork.

**Comment by elfring** [comment]
The program flow was expressed [in the source code](https://github.com/openSUSE/libzypp/blob/0e9af27ee52af01cda5351bac47d69d070df2668/zypp/KeyRing.cc#L496 "Checking KeyRing::Impl::verifyFileSignatureWorkflow()"). How can corresponding data processing surprises be explained better with information like the following?

Excerpt from file “zypper.log”:
```
…
2018-05-23 19:14:35 <1> Sonne(12023) [zypper] main.cc(main):74 ===== Hi, me zypper 1.14.4
2018-05-23 19:14:35 <1> Sonne(12023) [zypper] main.cc(main):75 ===== 'zypper' 'lu' =====
…
2018-05-23 19:14:50 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(publicKeyExists):351 No key [] in keyring /var/tmp/zypp.SmXbsE/zypp-general-krlqr3Cx
2018-05-23 19:14:50 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(verifyFileSignatureWorkflow):497 File [/var/cache/zypp/raw/SteppenläufergvxOzs/repodata/repomd.xml] ( repomd.xml ) signed with unknown key []
2018-05-23 19:15:01 <1> Sonne(12023) [zypper] prompt.cc(get_prompt_reply):334 reply empty, returning the default: no (1)
2018-05-23 19:15:01 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(verifyFileSignatureWorkflow):499 askUserToAcceptUnknownKey: 0
2018-05-23 19:15:01 <5> Sonne(12023) [zypp] Exception.cc(log):166 FileChecker.cc(operator()):143 THROW:    Signature verification failed for repomd.xml
…
```

**Comment by bzeller** [comment]
If you do not want to provide the current full zypper log file you can also move the current log file away and let the zypper run that shows the error create a new one, this log file will only contain informations about that one run.

**Comment by elfring** [comment]
I wonder still why the software can not work with data like the following (as desired)?

```
…
2018-05-23 19:14:50 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(getData):153 Found keys: {
2018-05-23 19:14:50 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(getData):153   [B88B2FD43DBDC284-53674dd4] [openSUSE Project Signing Key <opensuse@opensuse.org>] [expires: 
2024-05-02]
2018-05-23 19:14:50 <1> Sonne(12023) [zypp::KeyRing] KeyRing.cc(getData):153 }
…
```


The available debug output is longer than what would be actually needed for this clarification.
I am trying to find the information which is more relevant here.

**Comment by bzeller** [comment]
The files in  "/var/cache/zypp/raw/SteppenläufergvxOzs/repodata" would be interesting, especially the repodata.xml and repodata.xml.asc file.

**Comment by elfring** [comment]
Are these two files automatically deleted after a signature check failure?

**Comment by bzeller** [comment]
"<GnuPG> General error" , might be your gpg library is incompatible or outdated. Can you show me the output of: "zypper search -si gpg". 

There was a bug recently where gpgme did break zypper because of a behaviour change.

**Comment by elfring** [comment]
You gave another surprising background information.
* Would you like to refer to any other bug report here?
* How will the following data display help then?


```
Sonne:~ # zypper search -si gpg
…
S  | Name                | Type        | Version     | Arch   | Repository       
---+---------------------+-------------+-------------+--------+------------------
i+ | KGpg                | application |             | noarch | (System Packages)
i+ | gpg2                | package     | 2.2.6-1.1   | x86_64 | (System Packages)
i+ | gpg2-debuginfo      | package     | 2.2.6-1.1   | x86_64 | (System Packages)
i+ | gpg2-debugsource    | package     | 2.2.6-1.1   | x86_64 | (System Packages)
i+ | gpg2-lang           | package     | 2.2.6-1.1   | noarch | (System Packages)
i+ | gpgme               | package     | 1.10.0-2.1  | x86_64 | (System Packages)
i+ | gpgmepp5            | package     | 16.08.3-2.3 | x86_64 | (System Packages)
i+ | kgpg                | package     | 17.12.3-1.1 | x86_64 | (System Packages)
i+ | kgpg-lang           | package     | 17.12.3-1.1 | noarch | (System Packages)
i+ | libKF5QGpgme5       | package     | 16.08.3-2.3 | x86_64 | (System Packages)
i+ | libgpg-error-devel  | package     | 1.28-1.1    | x86_64 | (System Packages)
i+ | libgpg-error0       | package     | 1.28-1.1    | x86_64 | (System Packages)
i+ | libgpg-error0-32bit | package     | 1.28-1.1    | x86_64 | (System Packages)
i+ | libgpgme-devel      | package     | 1.10.0-1.1  | x86_64 | (System Packages)
i+ | libgpgme11          | package     | 1.10.0-1.1  | x86_64 | (System Packages)
i+ | libgpgmepp6         | package     | 1.10.0-1.1  | x86_64 | (System Packages)
i+ | libqgpgme7          | package     | 1.10.0-2.1  | x86_64 | (System Packages)
i+ | python2-gpgme       | package     | 0.3-2.1     | x86_64 | (System Packages)
```

**Comment by elfring** [comment]
Is my software configuration accidentally also affected from details which are mentioned in [a bug report like “repomd.xml GPG signature verification error: gpgme_op_verify()”](https://bugzilla.redhat.com/show_bug.cgi?id=1566988 "Checking GPG signature verification")?

**Comment by bzeller** [comment]
So, your libgpgme version is outdated, its very likely you got unlucky and got stuck at a point before the issue was resolved. You need to update your gpgme to resolve the issue. You can either download the rpms manually from the repositories and install them or you accept the unsigned repository information for now ( the package itself is signed too which will be checked at install time by rpm anyway ) and do a refresh.

**Comment by bzeller** [comment]
That is the bug i was referring to https://bugzilla.opensuse.org/show_bug.cgi?id=1089497

**Comment by elfring** [comment]
Thanks for [your link to this bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1089497 "libzypp tests failure with GnuPG 2.2.6").

I find it strange that signature checking was temporarily broken here.
:crystal_ball: Will the software evolution trigger any more consequences for safer management of corresponding dependencies?

**Comment by bzeller** [comment]
I think this issue is resolved. If not please feel free to reopen the bug.

**Comment by elfring** [comment]
* Will [the implementation of the function “KeyManagerCtx::Impl::verifyAndReadSignaturesFprs”](https://github.com/openSUSE/libzypp/blob/8d7c3f8c6cb11adcef876351806e8bfa3e88b0e6/zypp/KeyManager.cc#L87 "Update candidate") need any further development considerations?
* How do you think about to adjust the exception handling (instead of returning an empty string because of a signature check failure)?
