### ISSUE TITLE
Package download speed, any way to improve it?

### ISSUE THREAD

**Issue by fusion809** [openSUSE/libzypp#119]
Hi,

ZYpp is a great package manager, and I truly admire the work you folks do, but ZYpp is perhaps the slowest package manager at downloading packages as it doesn't support using aria2c to download them (although I know it once did) and it doesn't have support for multiple package downloads at once and it doesn't, at least by default, use delta RPMs. I'm presently using Tumbleweed and trying upgrade from 20180606 to 20180613 and it seems like it's going to take > 13 hours just to download the 4.6 GB packages in this upgrade. My net is capable of 5 MB/s downloads, but now I'm stuck at ~50-100KB/s as an average download speed. 

My question is, essentially, can this be improved? Or is this a feature that very few care about and hence what I'm asking is likely to fall on deaf ears? 

Thanks for your time,
Brenton

**Comment by mlandres** [comment]
Yes, we dropped the aria2c backend some years ago. The MultiCurl backend supports zsync transfers und metalink downloads. Did you set some speed limit (`download.max_download_speed` in `/etc/zypp/zypp.conf`)? What you describe would be tpo slow, even if you'd use just the plain libcurl backend.

(AFAIR the default for using deltarpms is true (`download.use_deltarpm`))

Can you provide us some zypper log (`/var/log/zypper.log`) showing these slow downloads?
(best created with `ZYPP_MEDIA_CURL_DEBUG=2` set in the environent)

**Comment by fusion809** [comment]
I set min download speed (102400 presently), but not max. Well the upgrade is over now so I'm guessing the zypper log is gone now. I can try installing a package (e.g. widelands) and show you how slow that is (as usually I get lousy download speeds with installs too, not just upgrades). I have tried increasing the max number of connections in /etc/zypp/zypp.conf (to 10, then 20), that didn't seem to make much difference. I also tried manually setting mirrors to those closest to me, that didn't help.

**Comment by fusion809** [comment]
Rofl, occasionally download speeds get above the usual 50-100 KB/s and they presently are for widelands. This happened a couple of times during the upgrade too, but usually it's short-lived. The zypper log is very large so I'm guessing it doesn't get deleted when a new zypp transaction occurs so here it is.

[zypper.zip](https://github.com/openSUSE/libzypp/files/2114738/zypper.zip)

**Comment by mlschroe** [comment]
The stuff you downloaded simply isn't on any mirror. So zypper is fine, but there seems to be an issue with the pushing of Tumbleweed to our mirrors.

**Comment by mlschroe** [comment]
I've heard that the mirror database on download.opensuse.org was lost and the admins are in the process of rebuilding it.

**Comment by fusion809** [comment]
Funny thing is that I get download speeds of >1MB/s in my openSUSE Leap 42.3 VM, so it does seem Tumbleweed-specific.

**Comment by mlandres** [comment]
Darix just mentioned it should be fixed for IPv4 clients, but not for IPv6. They are still working on it.

**Comment by fusion809** [comment]
Hooray I seem to be getting > 1MB/s download speeds on Tumbleweed now.

**Comment by mlandres** [comment]
closing

**Comment by mlandres** [comment]
> Zypper currently downloads chunks from up to 5 different mirrors for a single package IIRC, so sequential downloads should progress much faster.
They may set `ZYPP_MULTICURL=0` in the environment to turn off multicurl (metalink and zsync) and fall back to plain libcurl.
