### ISSUE TITLE
Is it possible to abort a zypper command with a Python hook ?

### ISSUE THREAD

**Issue by gigi206** [openSUSE/libzypp#137]
Is there a way to abort zypper command with a hook like this (**/usr/lib/zypp/plugins/commit/example.py**):
```python
#!/usr/bin/env python
#
# zypp plugin
#
import os
import sys
from zypp_plugin import Plugin

class MyPlugin(Plugin):
  def COMMITBEGIN( self, headers, body ):
    if True:
      self.ack()
    else:
      sys.stderr.write('Abort\n')
      sys.exit(1)

plugin = MyPlugin()
plugin.main()
```

**Comment by mlandres** [comment]
No. Commit plugins accompany commit, but they are not able to amend it.

**Comment by gigi206** [comment]
Thank you for your answer.

Is there a way to abort zypper command ?

**Comment by mlandres** [comment]
Only by killing zypper. Within COMMITBEGIN this might even work without data corruption. Once the transaction started the risk to damage the system is far higher.

**Comment by gigi206** [comment]
Thank you, it works by killing zypper.

Is there exists a simple way to print output ? 
I use /proc/ppid/fd/2 for printing a message before killing zypper

**Comment by mlandres** [comment]
BTW: You are aware that a commit plugin is driven by libzypp and libzpp is used by (at least) zypper, yast and PackageKit (i.e. desktopp updater applets). So be carefull whom you kill.

Whether the parents stderr is open for writing and whether this is visible to a user depends on the application. With yast(qt) it's probably not visible, with yast(ncurses) it messes up the screen and PackageKit (as it is a daemon) might have stderr closed (or redirected to some log). In general a commit plugin is not expected to communicate with the user.

**Comment by gigi206** [comment]
In my case the parent will be always Zypper.

I need to control zypper for many reasons.

One of them is that I use git to commit all changes in my **/etc** directory when I modify some files or I update my system.

If there are some files not committed before starting an update process (allow when a user do it manually but forbidden in automaticated case) then I abort and print an error message and write a message in syslog.

Thank you for all these precisions :)
