### ISSUE TITLE
set CURL_HTTP_VERSION_2TLS with curl >= 7.47.0

### ISSUE THREAD

**Issue by crrodriguez** [openSUSE/libzypp#141]
libzypp should use HTTP2 if available, that can be achived by setting CURL_HTTP_VERSION_2TLS 

"CURL_HTTP_VERSION_2TLS
Attempt HTTP 2 over TLS (HTTPS) only. libcurl will fall back to HTTP 1.1 if HTTP 2 can't be negotiated with the HTTPS server. For clear text HTTP servers, libcurl will use 1.1. (Added in 7.47.0)"

**Comment by mlandres** [comment]
This will be the default with curl-7.62.0.

**Comment by bzeller** [comment]
Out of curiousity , why CURL_HTTP_VERSION_2TLS and not CURL_HTTP_VERSION_2_0 ? This should make libcurl use HTTP2 for https and http requests. Note that libzypp might get chunks of a file from a http only server ( after receiving the checksum for that part over https in the metalink file before ).

**Comment by mlandres** [comment]
> DEFAULT
> Since curl 7.62.0: CURL_HTTP_VERSION_2TLS 

because it's the new curl default (and code15 still uses ~7.60.0)

**Comment by mlandres** [comment]
JFYI: Reverted in `libzypp-17.14.1` due to [Bug 1146027 - libzypp/libcurl: random segfaults](https://bugzilla.suse.com/show_bug.cgi?id=1146027).
