### ISSUE TITLE
Binary incompatible change when using libsolv-0.7

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/libzypp#142]
After
https://github.com/openSUSE/libzypp/commit/dba170d442166d652861f54086621217fec04461

zypp::sat::LookupAttr::iterator::dip_equal(detail::CDataiterator const&, detail::Dataiterator const&) const

exposes the type from libsolv-0.7, i.e. detail::CDataIterator changes from _DataIterator to s_DataIterator

https://bugzilla.opensuse.org/show_bug.cgi?id=1115469

**Comment by mlandres** [comment]
Already tracked in bugzilla [bsc#1115469](https://bugzilla.opensuse.org/show_bug.cgi?id=1115469).
