### ISSUE TITLE
build/doc/autodoc/libzypp.doxytag missing with CMake 3.14.0

### ISSUE THREAD

**Issue by gruenich** [openSUSE/libzypp#165]
With CMake 3.14, the file build/doc/autodoc/libzypp.doxytag ist not found and the installation breaks.
See for example:
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:L/libzypp/standard/x86_64
Some hints are given in a merge request:
https://build.opensuse.org/request/show/687545

**Comment by bzeller** [comment]
https://github.com/openSUSE/libzypp/pull/166

**Comment by bzeller** [comment]
Fixed in libzypp >= 17.11.3
