### ISSUE TITLE
Is here any code examples?

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/libzypp#173]
I read the code of zypper. But it is way too complex to understand. I am trying to make a simple GUI to show and upgrade Tumbleweed snapshots. Would like to know functions that provide `zypper dup` feature. Thanks!

**Comment by mlandres** [comment]
We don't maintain code examples, but we kept [this](https://github.com/openSUSE/libzypp/blob/master/tools/zypp-install.cc) in the tools directory. Might be a starting point.

**Comment by guoyunhe** [comment]
Thanks!
