### ISSUE TITLE
libzypp assumes rpmdb is in Berkeley DB format (rh#1766128)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libzypp#197]
From [RH#1766128](https://bugzilla.redhat.com/1766128):
> In libzypp-17.14.0 and upstream as of today, libzypp assumes that rpmdb has a file named `Packages` in several places in `zypp/target/rpm/RpmDb.cc`.
As of rpm >= 4.13, this is not a valid assumption.

There is some work going on to replace BDB in Fedora's RPM with one of the other backends for the RPMDB (likely the upcoming SQLite backend, but who knows?). It'd be great if the zypp stack was no longer assuming there was a specific rpmdb type.

**Comment by mlandres** [comment]
Already working on it...
