### ISSUE TITLE
hardware (modalias) dependencies clash with RPM use of comma

### ISSUE THREAD

**Issue by ptesarik** [openSUSE/libzypp#216]
For example, I want to install a package on the Raspberry Pi automatically. A suitable modalias is created for the RPi firmware alias:

```
rpi31:~ # cat /sys/devices/platform/soc/soc:firmware/modalias
of:NfirmwareT<NULL>Craspberrypi,bcm2835-firmwareCsimple-bus
```

However, it cannot be used in a `Supplements`, because it contains a comma, which is parsed as a separator by librpm. In other words, this line in a spec-file:

```
Supplements: modalias(of:NfirmwareT*Craspberrypi,bcm2835-firmwareC*)
```

is parsed as:

```
Supplements: modalias(of:NfirmwareT*Craspberrypi
Supplements: bcm2835-firmwareC*)
```

This does not work, of course. My current workaround is to replace the comma with a question mark, so that it matches, but that's not ideal. I would appreciate some sort of quoting (or substitution?) for characters that are reserved by RPM.

**Comment by mlschroe** [comment]
IIRC you can urlencode the modalias query, i.e. use `%2C` instead of `,`:
```
Supplements: modalias(of:NfirmwareT*Craspberrypi%2Cbcm2835-firmwareC*)
```

**Comment by ptesarik** [comment]
Oh, great, this works!

So, this is not a feature of RPM (which contains the urlencoded string), but the encoded rhs string is decoded before matching against the modalias list.

Is this behaviour documented anywhere? Closest I found was a note in the documentation of pattern packages (https://doc.opensuse.org/projects/libzypp/HEAD/zypp-pattern-packages.html), but that's not quite where people would search.

**Comment by mlandres** [comment]
Will add a page for it at https://doc.opensuse.org/projects/libzypp/HEAD/

**Comment by ptesarik** [comment]
Thank you very much!
