### ISSUE TITLE
Backward compatibility against old createrepo package

### ISSUE THREAD

**Issue by jerry-re** [openSUSE/libzypp#221]
https://github.com/openSUSE/libzypp/blob/27db92b2cfd9e6f667633dac851625c3c2e870bd/zypp/media/MediaCurl.cc#L116

I found that libzypp has an issue when it parse repomd.xml file which created by old createrepo(+modifyrepo) package.
Official createrepo "0.9.8" version's modifyrepo binary doesn't add 'size' tag in repomd.xml file when it runs.
However, same version's createrepo binary adds 'size' tag in repomd.xml file.
It means each files element could vary in repomd.xml by result.
(createrepo → modifyrepo)
Therefore, "OnMediaLocation" should have '0' filesize by default to avoid unexpected filesize checking exception.
In my case, it has wrong filesize and caught by 'fileSizeExceeded' checking.
Please make '0' by default if there is no 'size' tag in repomd.xml file.

**Comment by jerry-re** [comment]
https://github.com/openSUSE/libzypp/blob/67f55b474d67f77c1868955da8542a7acfa70a9f/zypp/parser/yum/RepomdFileReader.cc#L92

Obviously, each _filesize set here via reading 'size' tag.

**Comment by bzeller** [comment]
OnMediaLocation does not have a filesize property so I guess you are talking about the download size:
OnMediaLocation does have size 0 by default if the repomd.xml does not specify something else. The "downloadSize" property has ByteCount as type which has a default value of 0.

**Comment by jerry-re** [comment]
Yes, I am talking about download size and it read from repomd.xml file's tag.
I faced the issue in below repomd.xml case.
`
<?xml version="1.0" ?><repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm" xmlns:suse="http://novell.com/package/metadata/suse/common">
  <revision>1588747154</revision>
  <data type="primary">
    <checksum type="sha256">d4c4a17a9e297f41e54566bfa3bd08c7d7c561dc4bd91ec67d0ab1684fecdf27</checksum>
    <timestamp>1588747189</timestamp>
    <size>861059</size>
    <open-size>8825943</open-size>
    <open-checksum type="sha256">b3e42d5b524f6b2b2540578be98dfcb2018e9a3961cb719187ace200573c792f</open-checksum>
    <location href="repodata/d4c4a17a9e297f41e54566bfa3bd08c7d7c561dc4bd91ec67d0ab1684fecdf27-primary.xml.gz"/>
  </data>
  <data type="group">
    <location href="repodata/934dae79d0c7772854acf5fb835bb17865049c43ddbb03d019508f8f246ad13b-group.xml.gz"/>
    <checksum type="sha256">934dae79d0c7772854acf5fb835bb17865049c43ddbb03d019508f8f246ad13b</checksum>
    <timestamp>1588747215.57</timestamp>
    <open-checksum type="sha256">4ef494cf35bf72120840db7438bc1423623bc9075091e1b1fe625b5e0ae9e0c4</open-checksum>
  </data>
</repomd>
`
In this case, libzypp has a problem.
As you can see, there is no 'size' tag in "group" meatadata file so, it should be set as '0'.
However, expected file size is still '861059' because previous "primary" metadata 'size' tag was not '0'.

Eventually, to solve this problem, every single metadata property should have initialized.

**Comment by bzeller** [comment]
For every new `<data>` entry a new OnMediaLocation is generated, as you can see here:

**Comment by bzeller** [comment]
If possible you could upload the zypper log for the zypper command that failed, maybe we can figure out there what happend

**Comment by jerry-re** [comment]
I am using libzypp version '17.14.0'.
Since this is quite old version, it does not have initialization.
It looks initialization was added commit below.
https://github.com/openSUSE/libzypp/commit/19962ded2c70790fc0e7292221fa9255dd946c03

I added those 2 lines in '17.14.0' srcs and compile it and it works well.
`
    else if ( reader_r->nodeType() == XML_READER_TYPE_END_ELEMENT )
    {
      // xpath: /repomd/data
      if ( reader_r->name() == "data" )
      {
        if (_callback)
          _callback( _location, _type, _typeStr );

        return true;
      }
    }
`
→
`
    else if ( reader_r->nodeType() == XML_READER_TYPE_END_ELEMENT )
    {
      // xpath: /repomd/data
      if ( reader_r->name() == "data" )
      {
        if (_callback)
        {
          _callback( _location, _type, _typeStr );
          _location = OnMediaLocation();
          _typeStr.clear();
        }
        return true;
      }
    }
`
