### ISSUE TITLE
%posttrans scriptlets does not work, because of wrong invokation

### ISSUE THREAD

**Issue by uskovboris** [openSUSE/libzypp#265]
Try to launch posttrans script like 

%posttrans
touch %{_sysconfdir}/posttrans-test-completed

And we get the following error messages in 

Jul 06 14:15:17 INOIP4903 packagekitd[3138]: Entering install phase
Jul 06 14:15:17 INOIP4903 packagekitd[3138]: Install progress update: 1 of 1
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1800 audit(1594034117.578:279): pid=9050 uid=0 auid=4294967295 ses=4294967295 op="appraise_data" cause="missing-hash" comm="sh" name="/var/adm/update-scripts/posttransksJgTt/posttrans-test.rpmHDHnPd" dev="dm-0" ino=24705 res=0
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1300 audit(1594034117.578:279): arch=40000028 syscall=11 per=800000 success=no exit=-13 a0=614a20 a1=614d00 a2=614a68 a3=d22b2500 items=1 ppid=3138 pid=9050 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sh" exe="/bin/bash" key="x"
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1307 audit(1594034117.578:279):  cwd="/"
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1302 audit(1594034117.578:279): item=0 name="/var/adm/update-scripts/posttransksJgTt/posttrans-test.rpmHDHnPd" inode=24705 dev=fe:00 mode=0100700 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
Jul 06 14:15:18 INOIP4903 PackageKit[3138]: install-files transaction /8_eaccceae from uid 0 finished with success after 2668ms

**Comment by uskovboris** [comment]
Actually an attempt to execute the "%posttrans" scriptlet leads to launching a command

/bin/sh -c <path-to-file-with scriptlet>

but It should be

/bin/sh <path-to-file-with scriptlet>

without "-c"

**Comment by mlandres** [comment]
@uskovboris What issue do you need to solve? Why is '-c' a problem for %posttrans scripts but not for any other script zypp executes?

**Comment by uskovboris** [comment]
@mlandres As I investigated, problem is related with some types of IMA policy configurations, For example, the following policy configuration prevent unsigned script files execution:

   appraise func=FILE_MMAP mask=MAY_EXEC appraise_type=imasig

So, if we read file into the memory and then execute (when use "/bin/sh <path to .sh file>") the /bin/sh is executed and it is possible to executed the script (from trusted package manager and shell of cause.

**Comment by mlandres** [comment]
@uskovboris I'm closing #266. as a PR against DEV_NZYPP is not what you wanted to do. You don't need to redo the PR, I'm about to fix it...

**Comment by mlandres** [comment]
for libzypp-17.25.7
