### ISSUE TITLE
libzypp barfs on multiple baseurls specified on one line

### ISSUE THREAD

**Issue by berolinux** [openSUSE/libzypp#285]
In dnf, multiple baseurl URLs can be specified on one line, separated by whitespace and an optional comma, e.g.
`baseurl=http://mirror.openmandriva.org/cooker/repository/znver1/main/testing/ http://abf-downloads.openmandriva.org/cooker/repository/znver1/main/testing/`
or
`baseurl=http://mirror.openmandriva.org/cooker/repository/znver1/main/testing/, http://abf-downloads.openmandriva.org/cooker/repository/znver1/main/testing/`
libzypp barfs on this, saying "Invalid path name component".

Splitting the line into 2 lines,
```
baseurl=http://mirror.openmandriva.org/cooker/repository/znver1/main/testing/
        http://abf-downloads.openmandriva.org/cooker/repository/znver1/main/testing/
```
works in both zypper and dnf.

It would be nice if zypper would support all repo files deemed acceptable by dnf.

**Comment by mlandres** [comment]
We'll fix it.

**Comment by mlandres** [comment]
For libzypp-17.25.7
