### ISSUE TITLE
Provide compile-time switch to force the singletrans backend...

### ISSUE THREAD

**Issue by mlandres** [openSUSE/libzypp#340]

**Comment by Conan-Kudo** [comment]
For context: Zypper has been broken in Fedora with the standard backend since we started using transaction file triggers for ldconfig and various systemd things a few years ago. The new single-transaction backend that uses librpm for everything will theoretically fix this, so I'd like to forcibly switch Zypper to that.

**Comment by bzeller** [comment]
> For context: Zypper has been broken in Fedora with the standard backend since we started using transaction file triggers for ldconfig and various systemd things a few years ago. The new single-transaction backend that uses librpm for everything will theoretically fix this, so I'd like to forcibly switch Zypper to that.

Please keep in mind this very likely will break the zypp PackageKit plugin and is also still highly experimental.

**Comment by Conan-Kudo** [comment]
> > For context: Zypper has been broken in Fedora with the standard backend since we started using transaction file triggers for ldconfig and various systemd things a few years ago. The new single-transaction backend that uses librpm for everything will theoretically fix this, so I'd like to forcibly switch Zypper to that.
> 
> Please keep in mind this very likely will break the zypp PackageKit plugin and is also still highly experimental.

We don't ship the zypp PK backend in Fedora, so that's not a problem.

**Comment by mlandres** [comment]
Either `rpmbuild --with enable_preview_single_rpmtrans_as_default_for_zypper` 
or `cmake -DENABLE_PREVIEW_SINGLE_RPMTRANS_AS_DEFAULT_FOR_ZYPPER=1`
