### ISSUE TITLE
fatal error: zypp/parser/ParseException.h: No such file or directory

### ISSUE THREAD

**Issue by HougeLangley** [openSUSE/libzypp#372]
I build libzypp with these options.

`cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BUILD_TRANS=ON -DENABLE_BUILD_DOCS=OFF -DENABLE_ZSTD_COMPRESSION=ON -DENABLE_ZCHUNK_COMPRESSION=ON -DDISABLE_MEDIABACKEND_TESTS=ON -DENABLE_PREVIEW_SINGLE_RPMTRANS_AS_DEFAULT_FOR_ZYPPER=OFF
`

When I build zypper, no ParseException.h in /usr/include/zypp/parser/ directory. What options I missed? Thanks.

<img width="507" alt="截屏2022-01-10 01 50 43" src="https://user-images.githubusercontent.com/1161594/148694139-5584b40b-b254-442f-a2fe-1dcea4bc9a91.png">

**Comment by bzeller** [comment]
Thanks, seems while refactoring I broke the install path for this file.
