### ISSUE TITLE
Fedora Rawhide: libzypp test fails with yaml-cpp 0.7.0

### ISSUE THREAD

**Issue by hobbes1069** [openSUSE/libzypp#428]
I'm working on updating Fedora Rawhide to yaml-cpp 0.7.0 as it is required by the latest version of OpenColorIO.

I initially ran into an issue with yaml-cpp being properly detected but performed a quick fix with:
```
Index: libzypp-17.31.1/CMakeLists.txt
===================================================================
--- libzypp-17.31.1.orig/CMakeLists.txt
+++ libzypp-17.31.1/CMakeLists.txt
@@ -219,6 +219,10 @@ IF ( NOT YAML-CPP_FOUND)
   MESSAGE( FATAL_ERROR " yaml-cpp not found" )
 ELSE ( NOT YAML-CPP_FOUND)
   INCLUDE_DIRECTORIES(${YAML_CPP_INCLUDE_DIR})
+  IF ( NOT YAML_CPP_LIBRARIES)
+    # Must have been found by config insted of module, use target instead.
+	SET(YAML_CPP_LIBRARIES "yaml-cpp")
+  ENDIF( NOT YAML_CPP_LIBRARIES)
 ENDIF( NOT YAML-CPP_FOUND)
```

Now the build completes but I have a test failure:
39/91 Test #39: RpmPkgSigCheck_test ..............***Failed    0.12 sec

For full log see:
https://kojipkgs.fedoraproject.org//work/tasks/6312/94016312/build.log

**Comment by mlandres** [comment]
The build error does not seem to be related to the yaml issue.

The testcase verifies a few rpm packages (in tests/zypp/data/RpmPkgSigCheck/) . Rather than the expected `Header V3 RSA/SHA256 Signature, key ID b88b2fd43dbdc284: NOKEY` messages, rpm reports `Header RSA signature: BAD (package tag 268: invalid OpenPGP signature)`.

Which rpm version are you using?

**Comment by Conan-Kudo** [comment]
Based on the task logs: https://koji.fedoraproject.org/koji/taskinfo?taskID=94016312

It looks like we're on RPM 4.18.0. Oh, we're probably getting screwed over by Sequoia PGP: https://fedoraproject.org/wiki/Changes/RpmSequoia

**Comment by Conan-Kudo** [comment]
Looks like @pmatilai just reverted this Change to RPM a few hours ago: https://src.fedoraproject.org/rpms/rpm/c/581e8ac2ae6d600e606dc2ffe7cc04ac471be557

**Comment by hobbes1069** [comment]
Yes, a scratch build completed (noth with yaml-cpp 0.7.0) I've kicked off a new build now.

**Comment by hobbes1069** [comment]
In any case I think my patch in the OP is still relevant. There's probably more robust methods but it work.
