### ISSUE TITLE
Automatically provide x86_64 subarchitecture levels

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/libzypp#439]
Recently RPM has gained support for x86_64 subarchitecture levels (see https://github.com/rpm-software-management/rpm/pull/2315). These identify the CPU capabilities and allow via a GLIBC HWCAPS overlay to dynamically select more optimized shared libraries for loading. This functionality has been implemented in openSUSE Tumbleweed now. 

What is missing is that the libzypp stack is automatically adding a system provide when the host cpu is capable to execute this level. One could do that via the assembly code in the PR above, or by parsing the output of "ld.so --help" (which might be highly unstable). Unfortunately afaik there is no glibc interface to reliably query the glibc information. 

Please let me know if you're willing to implement this functionality as it could be useful to select those overlay libraries for supporting architectures automatically.

**Comment by Vogtinator** [comment]
> What is missing is that the libzypp stack is automatically adding a system provide when the host cpu is capable to execute this level. One could do that via the assembly code in the PR above, or by parsing the output of "ld.so --help" (which might be highly unstable). Unfortunately afaik there is no glibc interface to reliably query the glibc information.

If it's an option to rely on GCC specific builtins, then just `__builtin_cpu_supports("x86-64-vX")` is available since GCC 12.2.

**Comment by mlandres** [comment]
>  __builtin_cpu_supports("x86-64-vX") is available since GCC 12.2.

Unfortunately we need a solution that works for the whole Code15 family.

**Comment by mlandres** [comment]
I'll do.

**Comment by mlandres** [comment]
Thanks @Vogtinator
