### ISSUE TITLE
zypp should not use select

### ISSUE THREAD

**Issue by crrodriguez** [openSUSE/libzypp#447]
hi:

libzypp continues using select.. this is very problematic since if you ever get fd >= 1024 it will just crash. 
No it is not more than 1024 fds, but just add a single fd  with a higher number to a set will trigger the (now runtime) __fdelt_chk fortify check.

So, you either switch the code to whatever C++ event library is trusted today (boost.asio?? no idea) or  lower your caller's own rlimit_nofile so things fail before crashing.

**Comment by bzeller** [comment]
Thanks for the information, i'll switch the code to use poll() / epoll()
