### ISSUE TITLE
FTBFS against GCC 5 on Debian

### ISSUE THREAD

**Issue by sunweaver** [openSUSE/libzypp#48]
Please see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777980

The FTBFS against gcc 5 was report for libzypp 14.29.1-2. I will do a test build for latest upstream release during today (hopefully) and report back, if that issue has been resolved already.

**Comment by mlandres** [comment]
Should be fixed with 6f52bcbc8bdbe507b04f3205dc8ab67599f7e695 in 14.38.1

**Comment by jreidinger** [comment]
yep, the latest upstream release is used on opensuse TW and there is already gcc5, so it should work without issues on gcc5.

**Comment by jreidinger** [comment]
see https://news.opensuse.org/2015/06/16/default-compiler-for-tumbleweed-updates-to-gcc-5/

**Comment by sunweaver** [comment]
@jreidinger: @mlandres: I just did a test built against Debian experimental with my latest upload 15.3.0-1. Everything works. Thanks for your feedback.
