### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [openSUSE/libzypp#51]
I would like to point out that identifiers like "[`_PL`](https://github.com/openSUSE/libzypp/blob/bb67432eab34163ef3e520183792b83757722219/zypp/base/Gettext.h#L25)" and "[`_Report`](https://github.com/openSUSE/libzypp/blob/master/zypp/Callback.h#L163)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mlandres** [comment]
We'll fix them.
