### ISSUE TITLE
Test suite failures with libzypp 17.31.31 on Fedora Rawhide/F40

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libzypp#522]
When trying to update to libzypp 17.31.31 to fix the FTBFS with new Boost, I've encountered test suite failures with the new libzypp.

Test output log: [libzypp-17.31.31-fc41-checklog.txt](https://github.com/openSUSE/libzypp/files/14324283/libzypp-17.31.31-fc41-checklog.txt)

The package sources have been checked into OBS as well: https://build.opensuse.org/package/show/home:Pharaoh_Atem:Zypper_Fedora/libzypp

**Comment by mlandres** [comment]
```
unknown location(0): fatal error: in "msa_remote_tests_ftp": zypp::Exception: Failed to start the ftpserver
/builddir/build/BUILD/libzypp-17.31.31/tests/zypp/MediaSetAccess_test.cc(250): last checkpoint
*** 1 failure is detected in the test module "Master Test Suite"
```
@bzeller would you mind having a look at it.

**Comment by bzeller** [comment]
> ```
> unknown location(0): fatal error: in "msa_remote_tests_ftp": zypp::Exception: Failed to start the ftpserver
> /builddir/build/BUILD/libzypp-17.31.31/tests/zypp/MediaSetAccess_test.cc(250): last checkpoint
> *** 1 failure is detected in the test module "Master Test Suite"
> ```
> 
> @bzeller would you mind having a look at it.

For those tests vsftpd is required. That would be the first thing to check if that error is shown.

**Comment by Conan-Kudo** [comment]
The libzypp package in OBS I linked in the original post fully reproduces the issue.

**Comment by mlandres** [comment]
```
[zypp::media] MediaCurl.cc(doGetFileCopyFile):1268 curl error: 1: Received HTTP/0.9 when not allowed, temp file size 0 bytes.
[zypp-core] Exception.cc(log):186 MediaCurl.cc(evaluateCurlCode):963 THROW:    Download (curl) error for 'http://localhost:10001/complexdir/directory.yast':
[zypp-core] Exception.cc(log):186 Error code:  Unsupported protocol
[zypp-core] Exception.cc(log):186 Error message: Received HTTP/0.9 when not allowed
```
This seems the be the issue.

**Comment by mlandres** [comment]
@Conan-Kudo It appears to be independent from Boost. SUSE and Fedora use different defaults for the vsftpd's `background` option. This appears to cause the issues.
