### ISSUE TITLE
Feature request: flag for submodules in MountPoint

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/libzypp#54]
We have [this bug](https://bugzilla.suse.com/show_bug.cgi?id=949945) in the YaST team (see the screenshot attached there). The suggested solution is to simply not list btrfs subvolumes in that "Disk Usage" list. For generating the list we are using `zypp::DiskUsageCounter::detectMountPoints()`. For each entry in that list we can check a flag (`Hint_growonly`) to know if that entry is an btrfs snapshot.

Would you find reasonable to also have a flag to identify btfs subvolumes? Not only for the sake of our particular bug, but in general subvolumes add more noise than information to the space calculation.

If you are willing to include such functionality I can try to create a pull request. But beware I'm a Ruby developer not having touched C++ for ages, so better check my code twice. :-)

**Comment by mlandres** [comment]
I'll need have a closer look at the code, but I presume that the dynamic computation is also wrong if subvolumes are present. The code is pretty old and still assumes a 1-1 relation between mount point and device. Most probably I have to filter all subvolumes from the mountpoint list to get the computation right. This bugfix will resolve your issue was well.

**Comment by ancorgs** [comment]
I'm all for filtering the subvolumes out of the list of mountpoints. In most cases they only introduce noise.

There is only a corner case in which we could lose information, if [subvolume quotas](https://btrfs.wiki.kernel.org/index.php/Quota_support) are used. But IMHO, btrfs quotas are too complex to support them in DiskUsageCounter. Looks like you can specify limits for total data usage, for un-shared data usage, for compressed data usage... too much complexity.

**Comment by ancorgs** [comment]
BTW, @mlandres JFYI we have the mentioned YaST bug planned for the current Scrum sprint finishing at the end of January. :wink:

**Comment by mlandres** [comment]
Thanks for you patch. I'll re-use some part of it. But for now I will completely remove the subvolumes from the list. Otherwise the disk usage computation per package will break. Will be fixed in the next libzypp release; 15.20.1 before end of January ;)

**Comment by ancorgs** [comment]
@mlandres Cool! Thanks
