### ISSUE TITLE
Missing word in the Swedish Translation

### ISSUE THREAD

**Issue by bittin** [openSUSE/libzypp#551]
Hello!

just tested to install Tumbleweed when i tested Agama 8 and found out a translation is missing https://imgur.com/a/YuU9h4B of the word Continue to Fortsätt when running zypper in Swedish

but its translated on the Weblate: https://l10n.opensuse.org/translate/libzypp/master/sv/?q=Forts%C3%A4tt&sort_by=-priority%2Cposition&offset=3 since of 3 days ago, so would be good if you could sync in the latest translations :)

**Comment by mlandres** [comment]
@bittin weblate automatically syncs the translations back into our git and I can see it [here](https://github.com/openSUSE/libzypp/blob/master/po/sv.po#L4164-L4168). The sv.po was last touched on Apr 10 by you. So your changes (in libzypp) should be available since libzypp-17.32.3.

**Comment by bittin** [comment]
still was not fixed when i installed Tumbleweed with Agama earlier today, but maybe its not been pushed out yet

**Comment by mlandres** [comment]
Check with `zypper se -sx libzypp zypper`
I currently see libzypp-17.34.0-1.1 and zypper-1.14.73-1.2

It will need at least libzypp-17.34.1 and a recompiled zypper (1.14.73-1.3 or higher)

**Comment by bittin** [comment]
> Check with `zypper se -sx libzypp zypper` I currently see libzypp-17.34.0-1.1 and zypper-1.14.73-1.2
> 
> It will need at least libzypp-17.34.1 and a recompiled zypper (1.14.73-1.3 or higher)


test@localhost:~> zypper se -sx libzypp zypper
L\C3\A4ser in f\C3\B6rr\C3\A5dsdata...
L\C3\A4ser installerade paket...

S | Name    | Type  | Version     | Arch   | Repository
--+---------+-------+-------------+--------+---------------------------------------------------
i | libzypp | paket | 17.34.1-1.1 | x86_64 | https://download.opensuse.org/tumbleweed/repo/oss/
i | zypper  | paket | 1.14.73-1.2 | x86_64 | https://download.opensuse.org/tumbleweed/repo/oss/


ah guess i will wait until it lands then

**Comment by bittin** [comment]
> > Check with `zypper se -sx libzypp zypper` I currently see libzypp-17.34.0-1.1 and zypper-1.14.73-1.2
> > It will need at least libzypp-17.34.1 and a recompiled zypper (1.14.73-1.3 or higher)
> 
> test@localhost:~> zypper se -sx libzypp zypper L\C3\A4ser in f\C3\B6rr\C3\A5dsdata... L\C3\A4ser installerade paket...
> 
> S | Name | Type | Version | Arch | Repository --+---------+-------+-------------+--------+--------------------------------------------------- i | libzypp | paket | 17.34.1-1.1 | x86_64 | https://download.opensuse.org/tumbleweed/repo/oss/ i | zypper | paket | 1.14.73-1.2 | x86_64 | https://download.opensuse.org/tumbleweed/repo/oss/
> 
> ah guess i will wait until it lands then

@mlandres installed mullvadvpn via a community home repo on my now updated Leap 15.6 laptop before the openSUSE conference 2024 later this week and saw this has been fixed now :)
