### ISSUE TITLE
Make Helix repo support optional

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libzypp#56]
When building libzypp and Zypper for Fedora, it fails to build because Fedora's libsolv doesn't have Helix repo support. As far as I can tell, SUSE does not use the helix repo format, nor does it use `rug` anymore.

I'm hesitant to ask for libsolv to have support for this repo format added to libsolv when it's not really used anymore. Could libzypp and Zypper be modified so that they don't require it (and it can be enabled with a compile time flag, if needed)?

**Comment by mlandres** [comment]
libzypp uses Helix when writing/reading resolver testcases (`zypper in --debug-solver`)
