### ISSUE TITLE
"Signature verification failed for repomd.xml" on OpenMandriva

### ISSUE THREAD

**Issue by berolinux** [openSUSE/libzypp#593]
In current OpenMandriva builds (using libzypp 17.35.14 and zypper 1.14.78), verification of repositories' repomd.xml fails.

This affects both OpenMandriva's own repositories:
```
Error building the cache:
[cooker-x86_64|http://abf-downloads.openmandriva.org/cooker/repository/x86_64/main/release/] Failed to retrieve new repository metadata.
History:
 - Signature verification failed for repomd.xml
Warning: Skipping repository '"OpenMandriva Cooker - x86_64"' because of the above error.
```

and (more or less) distribution neutral vendor repositories like Brave's:
```
Error building the cache:
[brave|https://brave-browser-rpm-release.s3.brave.com/x86_64/] Failed to retrieve new repository metadata.
History:
 - Signature verification failed for repomd.xml
Warning: Skipping repository 'brave' because of the above error.
```

So far I've traced it to `KeyRingWorkflow::verifyFileSignature` failing inside `VerifySignatureLogic::MaybeAsyncRef<expected<zypp::keyring::VerifyFileContext>> execute` (hitting the `not res.first` code path).

Potentially relevant versions of external libraries:
glibc 2.40
libassuan 3.0.1
boost 1.86.0
brotli 1.1.0
openssl 3.4.0
curl 8.11.0
gcrypt 1.11.0
libgpg-error 1.50
gpgme 1.24.0
rpm 4.20.0

dnf (both 4.x and 5.x) works fine on the same box with the same repositories.

**Comment by mlandres** [comment]
@berolinux preferably open a [bugreport](https://bugzilla.suse.com/enter_bug.cgi?product=openSUSE%20Tumbleweed) for component libzypp or zypper and attach the /var/log/zypper.log showing this issue. 

On my system the repo fails as well, but not in `Signature verification` but when creating the solv cache. Without being able to repeoduce it, we need to see the log.

**Comment by mlandres** [comment]
It works for me as expected if I follow the instructions on [https://brave.com/linux/](https://brave.com/linux/).
```
0d24de619319:/ # rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

0d24de619319:/ # zypper addrepo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
Adding repository 'Brave Browser' .........................................................................................................................................[done]
Repository 'Brave Browser' successfully added

URI         : https://brave-browser-rpm-release.s3.brave.com/x86_64
Enabled     : Yes
GPG Check   : Yes
Autorefresh : Yes
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.

0d24de619319:/ # zypper ref
Retrieving repository 'brave' metadata ....................................................................................................................................[done]
Building repository 'brave' cache .........................................................................................................................................[done]
Retrieving repository 'Brave Browser' metadata ............................................................................................................................[done]
Building repository 'Brave Browser' cache .................................................................................................................................[done]
All repositories have been refreshed.
```
If it nevertheless fails for you, please provide you /var/log/zypper.log.

**Comment by AngryPenguinPL** [comment]
> If it nevertheless fails for you, please provide your /var/log/zypper.log.

I have same problem. We both use distro OpenMandriva.

Here is my zypper.log from last session after running "zypper refresh"

Log: https://gist.github.com/AngryPenguinPL/73d6dddbc679b86234ed2b99eb0e29c5

**Comment by mlandres** [comment]
@AngryPenguinPL according to the log you should have seen the `Do you want to reject the key, or trust always? [r/a/?] (r):` for each repo and always answered with the default `r` to reject the key (and so the repo). Is this true?

OTOH the initialization of the rpmdb (which stores the trusted keys) is kind of strange. The rpm `%{_dbpath}` macro says `/var/lib/rpm`. The directory seems to exist, but we don't get access to the database. Could you provide the output of `ls -l /var/lib/rpm /usr/lib/sysimage/rpm` so I can check it.

**Comment by berolinux** [comment]
The `%{_dbpath}` macro is set correctly, the rpm database lives in `/var/lib/rpm`.

```
[bero@ryzen9 ~]$ ls -l /var/lib/rpm
total 579112
drwxr-xr-x 2 root root      4096 Dec  3 21:58 filetriggers
-rw-r--r-- 1 rpm  rpm  592969728 Dec  5 17:38 rpmdb.sqlite
-rw-r--r-- 1 rpm  rpm      32768 Dec  5 17:38 rpmdb.sqlite-shm
-rw-r--r-- 1 rpm  rpm          0 Dec  5 17:38 rpmdb.sqlite-wal
```

I've never seen a `Do you want to reject the key, or trust always?` prompt -- maybe that's where the problem is coming from (somehow it thinks it has already asked, and been told to reject the key, when in fact it never asked). Where do the answers to that question get stored?

**Comment by mlandres** [comment]
A `rpmdb.sqlite`? Zypp is not prepared for detecting this. 

If you dare, touch `/var/lib/rpm/Packages` (or `Packages.db`). This will make zypp believe a database is present. We just check for the presence of one of those files.

If this makes the refresh work, please try `rm -r /var/cache/zypp/solv/@System/; zypper se -i`. This will force libsolv to rebuild the rpmdb cache. If this does not work either, we'll need a fix for libsolv as well.

**Comment by mlandres** [comment]
> Where do the answers to that question get stored?

As response to a positive answer, trusted keys are stored as `gpg-pubkey` pseudo package in the rpmdb (`rpm --import KEY`). Rpm uses those keys to verify a packages signature (in case it is signed). Zypp accepts metadata signed with trusted keys. 

If we don't see the rpmdb we don't have trusted keys. This should lead to the question whether you want to trust the key (in case the repo is signed).

**Comment by mlandres** [comment]
libzypp-17.35.15 will recognize rpmdb.sqlite as a database file. Maybe this already solves the issue.
If it does not work for you, please provide the /var/log/zypper.log.

**Comment by AngryPenguinPL** [comment]
it looks like this commit solved the problem.

I have one more minor problem though. Namely, after accepting an operation like installing a package or updating the system, no information about the progress appears. That is, from the moment I press the "y" key and confirm with enter, zypper does not display anything else, nor does it show the speed at which the package is being downloaded, nor how many % has been downloaded, nor does it provide information about the installation/update itself. But packages are installed successfully.

I remember that some time ago it worked fine.

But I guess I should open another a bug report for this?
