### ISSUE TITLE
Many libzypp unit test failures on Fedora

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libzypp#67]
When doing [a scratch build of libzypp](https://koji.fedoraproject.org/koji/taskinfo?taskID=18035093) with the unit tests enabled, there are several unit tests that fail.

The failure report is as follows:

```
81% tests passed, 14 tests failed out of 73
Total Test time (real) =  39.77 sec
The following tests FAILED:
	  5 - Capabilities_test (Failed)
	 12 - Deltarpm_test (Failed)
	 17 - InstanceId_test (Failed)
	 20 - Locks_test (Failed)
	 25 - PoolQuery_test (Failed)
	 31 - RepoManager_test (Failed)
	 39 - Target_test (Failed)
	 59 - ExtendedMetadata_test (Failed)
	 62 - DUdata_test (Failed)
	 66 - LookupAttr_test (Failed)
	 67 - Pool_test (Failed)
	 70 - Solvable_test (Failed)
	 71 - SolvParsing_test (Failed)
	 73 - WhatProvides_test (Failed)
Errors while running CTest

```

Full build log for x86_64 attached: [libzypp-16.4.3-build.log.txt](https://github.com/openSUSE/libzypp/files/800188/libzypp-16.4.3-build.log.txt)

Other build logs are [viewable from Fedora Koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=18035093).

**Comment by mlandres** [comment]
Maybe something due to the way your libsolv is configured. Within the build tree, check `tests/Testing/Temporary/LastTest.log`. It should reveal in detail which checks failed within the tests. If this does not explain the problem one has to dig deeper... (JFYI on vacation till March 6.)

**Comment by Conan-Kudo** [comment]
It doesn't seem like a "libsolv is configured wrongly" type of issue.

Here's our libsolv switches (we're on libsolv 0.6.26):

```
-DFEDORA=1 
-DENABLE_RPMDB=ON 
-DENABLE_RPMDB_BYRPMHEADER=ON 
-DENABLE_RPMMD=ON 
-DENABLE_COMPS=ON 
-DUSE_VENDORDIRS=ON 
-DENABLE_LZMA_COMPRESSION=ON 
-DENABLE_BZIP2_COMPRESSION=ON 
-DENABLE_HELIXREPO=ON 
-DENABLE_SUSEREPO=ON 
-DENABLE_DEBIAN=ON 
-DENABLE_ARCHREPO=ON 
-DMULTI_SEMANTICS=ON 
-DENABLE_COMPLEX_DEPS=1 
-DENABLE_PERL=ON 
-DENABLE_RUBY=ON 
-DENABLE_PYTHON=ON 
-DENABLE_PYTHON3=ON
```

The [LastTest.log](https://github.com/openSUSE/libzypp/files/803524/libzypp-16.4.3-LastTest.log.txt) file indicates something interesting, though. Each of the failed tests have either `zypp::repo::RepoException: Failed to cache repo (129).` or `zypp::Exception: Failed to cache rpm database (129).`.

**Comment by mlandres** [comment]
Are libsolv tools installed (rpmdb2solv/repo2solv.sh)?
Can you run one of the failing test manually with `ZYPP_LOGFILE=/tmp/zypp.log` in the environment? The log file should tell what's missing.

**Comment by Conan-Kudo** [comment]
@mlandres Ah, that was it. Installing `libsolv-tools` into the build environment made all the tests pass!

Thanks!
