### ISSUE TITLE
DigestReport does not provide repository; impossible to fix YaST2 bug until it does

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/libzypp#78]
I'm guessing that https://bugzilla.opensuse.org/show_bug.cgi?id=500134 is still valid, but I'm reopening it here in the hopes of getting more attention. Please refer to the original bug report for details.

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
