### ISSUE TITLE
failure to refresh repositories with GnuPG 2.1.23

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/libzypp#80]
zypper fails to refresh repositories with GnuPG 2.1.23 (only). This is new behavior with 2.1.23.

Combination tested:

- openSUSE Leap 42.3
- security:privacy/openSUSE_Leap_42.3
- gpg2-2.1.23 from `home:AndreasStieger:branches:security:privacy/gpg2`
- `zypper ref -f` (any)..

```
zypper ref -f 14
Forcing raw metadata refresh
Retrieving repository 'update-test' metadata     
File 'repomd.xml' from repository 'update-test' is signed with an unknown key ''. Continue? [yes/no] (no): 
```

The GnuPG version seems to operate normally otherwise, but something in the behavior or output changed to break the zypper/libzypp scenario.

**Comment by mlandres** [comment]
@andreasstieger Please open a bugreport at https://bugzilla.suse.com and attach the zypper log. Especially as our package submission policy asks for bugzilla references in the changes file, we preferably track in bugzilla.

**Comment by andreasstieger** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1054088
